### ISSUE TITLE
Use amazon S3 locally

### ISSUE THREAD

**Issue by mitramejia** [anttiviljami/wordpress-heroku-docker-project#10]
After configuring the project and making a deploy to heroku, I've started working with the local installation to find out it's not uploading any images. At heroku it works as expected.

![screen shot 2018-02-02 at 11 29 22 am](https://user-images.githubusercontent.com/2616517/35740800-5fddffce-080c-11e8-867b-4adc47625079.png)

So I ssh'd into the `web` container and changed the permisions to 755 for `wp-content/` 
but the error persists. 

Maybe I'm missing something obvious?

**Comment by mitramejia** [comment]
Fixed it by using the method described in [S3-Uploads](https://github.com/humanmade/S3-Uploads#offline-development) Readme. When environment is `local` use the wordpress mechanism to handle media uploads. If not use Amazon S3

In `config/wp-config.php` 

It would look like this

![screen shot 2018-02-02 at 4 04 05 pm](https://user-images.githubusercontent.com/2616517/35752547-bff7b384-0832-11e8-9922-05762d1487ee.png)



Should we make this a default for the project? Let me know, I'd be happy to submit a PR

**Comment by k1sul1** [comment]
I had to chmod uploads to 777 in order to get them to work. It probably doesn't have to be 777 but I didn't really care.
