### ISSUE TITLE
Plugins not finding wp-content folder

### ISSUE THREAD

**Issue by mitramejia** [anttiviljami/wordpress-heroku-docker-project#11]
Some plugins were not finding the wp-content folder. To solve this I explicitly defined the `wp-content` folder in `wp-config.php`

`define( 'WP_CONTENT_DIR', $webroot_dir . '/wp-content' );`

Should I open a pull request with this change?

**Comment by anttiviljami** [comment]
Sorry for super late reply. I don't see any issue with this if you want to submit a PR :) Closing the issue, since I haven't personally run into any issues without this change.
