### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by r-freeman** [anttiviljami/wordpress-heroku-docker-project#13]
Followed all the steps in the readme but browsing to http://localhost:8080 gives the error above.

**Comment by gregvissing** [comment]
> Followed all the steps in the readme but browsing to http://localhost:8080 gives the error above.

Did you find a fix to this issue? I'm running into the same problem.

**Comment by r-freeman** [comment]
Nope didn't find a fix for this sadly

**Comment by anttiviljami** [comment]
Hi! Sorry for being so slow to react to this issue. Closing this, since it's more than 3 months old now but feel free to open a new one if you wish!
