### ISSUE TITLE
AWS stack is failing

### ISSUE THREAD

**Issue by MurhafSousli** [anttiviljami/wordpress-heroku-docker-project#2]
Hi @anttiviljami, First thank you for this project
I followed your video tutorial step by step, I signed up for aws but when I create a stack I get 

Status:
`ROLLBACK_IN_PROGRESS`

in events:

![image](https://user-images.githubusercontent.com/8130692/26967643-aec8eae2-4d07-11e7-9cad-95e0dee7f6f0.png)

Do you have any idea why I'm getting this?

I also want to ask, In order to push changes to **heroku**, I am supposed to push them to GitHub so they get deployed automatically, right! so do I fork your repo, or do I create my own and push the files to it?

**Comment by MurhafSousli** [comment]
Okay I got it, I was using an existing bucket name 😅

**Comment by anttiviljami** [comment]
:+1:
