### ISSUE TITLE
After edit theme files there is no changes.

### ISSUE THREAD

**Issue by thomkrupa** [anttiviljami/wordpress-heroku-docker-project#5]
Hello, 

I'm trying develop theme on this excellent stack. But I have problem - after edit file and save it I refresh local page and... nothing. I have to pause docker-compose and again type "docker-compose up web". Any idea how to fix it? It's very frustrating.

**Comment by anttiviljami** [comment]
Just update to the newest version of this repo :)

Fixed by this: https://github.com/anttiviljami/wordpress-heroku-docker-project/commit/51e410378094430847930ef4b45e43679e367212
